/** Staff picks up at customer home → shop → processing → return (staff or Picki runner). */
export const LAUNDRY_HOME_PICKUP_TRANSITIONS: Record<string, string[]> = {
  CREATED: ["PAYMENT_PENDING", "PROVIDER_ACCEPTED", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  PAYMENT_PENDING: ["PAID", "PAYMENT_FAILED", "CUSTOMER_CANCELLED"],
  PAID: ["PROVIDER_ACCEPTED", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  PROVIDER_ACCEPTED: ["AT_SHOP", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  AT_SHOP: ["PROCESSING"],
  PROCESSING: ["READY_FOR_RETURN"],
  READY_FOR_RETURN: ["RETURN_DELIVERING", "RETURN_RUNNER_ASSIGNED", "CUSTOMER_CANCELLED"],
  RETURN_RUNNER_ASSIGNED: ["RETURN_PICKED_UP"],
  RETURN_PICKED_UP: ["RETURN_DELIVERING"],
  RETURN_DELIVERING: ["COMPLETED"],
  PAYMENT_FAILED: [],
  PROVIDER_REJECTED: [],
  CUSTOMER_CANCELLED: [],
  SYSTEM_CANCELLED: [],
  REFUND_PENDING: ["REFUNDED"],
  REFUNDED: [],
  DELIVERED: [],
  COMPLETED: [],
};

/** Customer brings items to shop — skip inbound leg. */
export const LAUNDRY_SHOP_DROP_OFF_TRANSITIONS: Record<string, string[]> = {
  CREATED: ["PAYMENT_PENDING", "PROVIDER_ACCEPTED", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  PAYMENT_PENDING: ["PAID", "PAYMENT_FAILED", "CUSTOMER_CANCELLED"],
  PAID: ["PROVIDER_ACCEPTED", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  PROVIDER_ACCEPTED: ["AT_SHOP", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  AT_SHOP: ["PROCESSING"],
  PROCESSING: ["READY_FOR_RETURN"],
  READY_FOR_RETURN: ["RETURN_DELIVERING", "RETURN_RUNNER_ASSIGNED", "CUSTOMER_CANCELLED"],
  RETURN_RUNNER_ASSIGNED: ["RETURN_PICKED_UP"],
  RETURN_PICKED_UP: ["RETURN_DELIVERING"],
  RETURN_DELIVERING: ["COMPLETED"],
  PAYMENT_FAILED: [],
  PROVIDER_REJECTED: [],
  CUSTOMER_CANCELLED: [],
  SYSTEM_CANCELLED: [],
  REFUND_PENDING: ["REFUNDED"],
  REFUNDED: [],
  DELIVERED: [],
  COMPLETED: [],
};

/** Sofa / thảm / đệm — provider giặt tại nhà khách. */
export const LAUNDRY_ON_SITE_TRANSITIONS: Record<string, string[]> = {
  CREATED: ["PAYMENT_PENDING", "PROVIDER_ACCEPTED", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  PAYMENT_PENDING: ["PAID", "PAYMENT_FAILED", "CUSTOMER_CANCELLED"],
  PAID: ["PROVIDER_ACCEPTED", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  PROVIDER_ACCEPTED: ["PROCESSING", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  PROCESSING: ["COMPLETED"],
  PAYMENT_FAILED: [],
  PROVIDER_REJECTED: [],
  CUSTOMER_CANCELLED: [],
  SYSTEM_CANCELLED: [],
  REFUND_PENDING: ["REFUNDED"],
  REFUNDED: [],
  DELIVERED: [],
  COMPLETED: [],
};

/** @deprecated use LAUNDRY_HOME_PICKUP_TRANSITIONS */
export const LAUNDRY_INBOUND_TRANSITIONS = LAUNDRY_HOME_PICKUP_TRANSITIONS;

export type ServiceVertical = "FOOD" | "LAUNDRY";
export type LaundryPickupMode = "HOME_PICKUP" | "SHOP_DROP_OFF" | "ON_SITE";

export function laundryTransitionsForMode(mode: LaundryPickupMode | null | undefined) {
  if (mode === "SHOP_DROP_OFF") return LAUNDRY_SHOP_DROP_OFF_TRANSITIONS;
  if (mode === "ON_SITE") return LAUNDRY_ON_SITE_TRANSITIONS;
  return LAUNDRY_HOME_PICKUP_TRANSITIONS;
}

/** Khách hủy được trước khi tiệm nhận/lấy đồ (chưa AT_SHOP / chưa PROCESSING tại nhà). */
export function canLaundryCustomerCancelBeforeCollection(
  status: string,
  mode?: LaundryPickupMode | null,
): boolean {
  if (mode === "ON_SITE") {
    return status === "CREATED" || status === "PROVIDER_ACCEPTED";
  }
  return status === "CREATED" || status === "PROVIDER_ACCEPTED";
}
