/** Laundry with runner pickup at customer home → shop → processing → return to customer. */
export const LAUNDRY_HOME_PICKUP_TRANSITIONS: Record<string, string[]> = {
  CREATED: ["PAYMENT_PENDING", "PROVIDER_ACCEPTED", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  PAYMENT_PENDING: ["PAID", "PAYMENT_FAILED", "CUSTOMER_CANCELLED"],
  PAID: ["PROVIDER_ACCEPTED", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  PROVIDER_ACCEPTED: ["RUNNER_ASSIGNED", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  RUNNER_ASSIGNED: ["PICKED_UP", "CUSTOMER_CANCELLED"],
  PICKED_UP: ["DELIVERING"],
  DELIVERING: ["AT_SHOP"],
  AT_SHOP: ["PROCESSING"],
  PROCESSING: ["READY_FOR_RETURN"],
  READY_FOR_RETURN: ["RETURN_RUNNER_ASSIGNED", "CUSTOMER_CANCELLED"],
  RETURN_RUNNER_ASSIGNED: ["RETURN_PICKED_UP"],
  RETURN_PICKED_UP: ["RETURN_DELIVERING"],
  RETURN_DELIVERING: ["COMPLETED"],
  PAYMENT_FAILED: [],
  PROVIDER_REJECTED: [],
  CUSTOMER_CANCELLED: [],
  SYSTEM_CANCELLED: [],
  REFUND_PENDING: ["REFUNDED"],
  REFUNDED: [],
  DELIVERED: [],
  COMPLETED: [],
};

/** Customer brings items to shop — skip inbound runner leg. */
export const LAUNDRY_SHOP_DROP_OFF_TRANSITIONS: Record<string, string[]> = {
  CREATED: ["PAYMENT_PENDING", "PROVIDER_ACCEPTED", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  PAYMENT_PENDING: ["PAID", "PAYMENT_FAILED", "CUSTOMER_CANCELLED"],
  PAID: ["PROVIDER_ACCEPTED", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  PROVIDER_ACCEPTED: ["AT_SHOP", "PROVIDER_REJECTED", "CUSTOMER_CANCELLED"],
  AT_SHOP: ["PROCESSING"],
  PROCESSING: ["READY_FOR_RETURN"],
  READY_FOR_RETURN: ["RETURN_RUNNER_ASSIGNED", "CUSTOMER_CANCELLED"],
  RETURN_RUNNER_ASSIGNED: ["RETURN_PICKED_UP"],
  RETURN_PICKED_UP: ["RETURN_DELIVERING"],
  RETURN_DELIVERING: ["COMPLETED"],
  PAYMENT_FAILED: [],
  PROVIDER_REJECTED: [],
  CUSTOMER_CANCELLED: [],
  SYSTEM_CANCELLED: [],
  REFUND_PENDING: ["REFUNDED"],
  REFUNDED: [],
  DELIVERED: [],
  COMPLETED: [],
};

/** @deprecated use LAUNDRY_HOME_PICKUP_TRANSITIONS */
export const LAUNDRY_INBOUND_TRANSITIONS = LAUNDRY_HOME_PICKUP_TRANSITIONS;

export type ServiceVertical = "FOOD" | "LAUNDRY";
export type LaundryPickupMode = "HOME_PICKUP" | "SHOP_DROP_OFF";

export function laundryTransitionsForMode(mode: LaundryPickupMode | null | undefined) {
  return mode === "SHOP_DROP_OFF"
    ? LAUNDRY_SHOP_DROP_OFF_TRANSITIONS
    : LAUNDRY_HOME_PICKUP_TRANSITIONS;
}
