/** Backend module boundaries — Master Spec §132. Empty until owning sprint. */
export const pickiModuleNames = [
  "auth",
  "users",
  "zones",
  "zone-planner",
  "addresses",
  "households",
  "geo",
  "providers",
  "catalog",
  "availability",
  "discovery",
  "search",
  "reviews",
  "orders",
  "bookings",
  "requests",
  "quotes",
  "classifieds",
  "payments",
  "billing",
  "runners",
  "fulfillment",
  "routing",
  "trust",
  "notifications",
  "messaging",
  "analytics",
  "support",
  "admin",
] as const;

export type PickiModuleName = (typeof pickiModuleNames)[number];
